spring:
  datasource:
    url: jdbc:mysql://localhost:3306/llmchat
    username: root
    password: root

llmchat:
  auth:
    jwt-secret: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecr
    kakao:
      client-id: dummy-client-id
