server:
  port: 8080
  shutdown: graceful

spring:
  profiles:
    default: local
  application:
    name: llmchat
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_batch_fetch_size: 1000
    open-in-view: false
  ai:
    openai:
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
    vectorstore:
      chroma:
        initialize-schema: true
        client:
          host: http://localhost
          port: 8000
  web:
    resources:
      add-mappings: false
