name: llmchat
services:
  mysql:
    image: mysql:8.0.36
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: llmchat
    volumes:
      - mysql-data:/var/lib/mysql

  chroma:
    image: chromadb/chroma:latest
    ports:
      - 8000:8000
    volumes:
      - chroma-data:/chroma/chroma
    environment:
      - ALLOW_RESET=true
      - ANONYMIZED_TELEMETRY=false

volumes:
  mysql-data:
  chroma-data:
